server/apps/barcode/urls.py
from django.urls import path

from . import views

app_name = "barcode"
urlpatterns = [
    path("api", views.Barcode.as_view(), name="api"),
]

server/apps/common/urls.py
from django.urls import path

from . import views

app_name = "common"

urlpatterns = [
    path("", views.Index.as_view(), name="index"),
]

server/apps/qrcode/urls.py
from django.urls import path

from . import views

app_name = "qrcode"
urlpatterns = [
    path("api", views.QRcode.as_view(), name="api"),
]

server/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.common.urls")),
    path("qrcode/", include("apps.qrcode.urls")),
    path("barcode/", include("apps.barcode.urls")),
]

server/apps/barcode/models.py
from django.db import models

# Create your models here.

server/apps/common/models.py
from django.db import models

# Create your models here.

server/apps/qrcode/models.py
from django.db import models

# Create your models here.

server/apps/barcode/views.py
from django.core.exceptions import BadRequest
from django.core.handlers.wsgi import WSGIRequest
from django.http import HttpResponse
from django.views.generic import TemplateView
from lib.generate import generate_barcode


class Index(TemplateView):
    template_name = "common/index.html"


class Barcode(TemplateView):
    def get(self, request: WSGIRequest) -> HttpResponse:
        if not (data := request.GET.get("data")):
            data = "No data provided"
        if not (name := request.GET.get("type")):
            name = "CODE128"
        try:
            svg = generate_barcode(data, name)
            return HttpResponse(svg, content_type="image/svg+xml")
        except Exception as error:
            raise BadRequest(error)

server/apps/common/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView


class Index(TemplateView):
    template_name = "common/index.html"

server/apps/qrcode/views.py
from django.core.handlers.wsgi import WSGIRequest
from django.http import HttpResponse
from django.views.generic import TemplateView
from lib.generate import generate_QRcode


class Index(TemplateView):
    template_name = "common/index.html"


class QRcode(TemplateView):
    def get(self, request: WSGIRequest) -> HttpResponse:
        if not (data := request.GET.get("data")):
            data = "No data provided"
        svg = generate_QRcode(data)
        return HttpResponse(svg, content_type="image/svg+xml")

server/apps/common/templates/common/index.html
{% extends 'base.html' %}
<!--  -->

{% block main %}

<div class="container">
  <div class="images">
    <img
      id="tabpanel-qrcode-image"
      class="tab-images"
      src="{% url 'qrcode:api' %}"
      aria-labelledby="tab-qrcode"
      aria-selected="true"
      alt="QRcode"
    />

    <img
      id="tabpanel-barcode-image"
      class="tab-images"
      src="{% url 'barcode:api' %}"
      aria-labelledby="tab-barcode"
      aria-selected="false"
      alt="Barcode"
      hidden
    />
  </div>

  <div class="tabs">
    <div class="tablist" role="tablist" aria-label="Image Code Forms Tabs">
      <button
        role="tab"
        tabindex="0"
        id="tab-qrcode"
        class="tab"
        aria-selected="true"
        data-content="qrcode"
        aria-controls="tabpanel-qrcode"
      >
        QRcode
      </button>
      <button
        role="tab"
        tabindex="-1"
        id="tab-barcode"
        class="tab"
        aria-selected="fa"
        data-content="barcode"
        aria-controls="tabpanel-barcode"
      >
        Barcode
      </button>
    </div>
    <div class="panels">
      <div
        role="tabpanel"
        tabindex="0"
        class="tabpanel"
        id="tabpanel-qrcode"
        aria-labelledby="tab-qrcode"
      >
        <form id="qrcode-form">
          <div class="form-group">
            <label for="qrcode-data">Data</label>
            <input id="qrcode-data" type="text" name="data" />
          </div>

          <div class="form-group">
            <button
              id="qrcode-generate"
              class="btn btn-secondary"
              type="submit"
            >
              Generate
            </button>
            <button id="qrcode-download" class="btn btn-primary">
              Download
            </button>
            <a id="qrcode-link" class="download"> </a>
          </div>
        </form>
      </div>

      <div
        role="tabpanel"
        tabindex="0"
        class="tabpanel"
        id="tabpanel-barcode"
        aria-labelledby="tab-barcode"
        hidden
      >
        <form id="barcode-form">
          <div class="form-group">
            <label for="barcode-data">Data</label>
            <input id="barcode-data" type="text" name="data" />
          </div>

          <div class="form-group">
            <label for="barcode-type">Type</label>
            <select id="barcode-type" name="type">
              <option value="code128" selected>CODE128</option>
              <option value="codabar">CODABAR</option>
              <option value="code39">CODE39</option>
              <option value="ean">EAN</option>
              <option value="ean13">EAN13</option>
              <option value="ean13-guard">EAN13-GUARD</option>
              <option value="ean14">EAN14</option>
              <option value="ean8">EAN8</option>
              <option value="ean8-guard">EAN8-GUARD</option>
              <option value="gs1">GS1</option>
              <option value="gs1_128">GS1_128</option>
              <option value="gtin">GTIN</option>
              <option value="isbn">ISBN</option>
              <option value="isbn10">ISBN10</option>
              <option value="isbn13">ISBN13</option>
              <option value="issn">ISSN</option>
              <option value="itf">ITF</option>
              <option value="jan">JAN</option>
              <option value="nw-7">NW-7</option>
              <option value="pzn">PZN</option>
              <option value="upc">UPC</option>
              <option value="upca">UPCA</option>
            </select>
          </div>

          <div class="form-group">
            <button
              id="barcode-generate"
              class="btn btn-secondary"
              type="submit"
            >
              Generate
            </button>
            <button id="barcode-download" class="btn btn-primary">
              Download
            </button>
            <a id="barcode-link" class="download"> </a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock main %}

server/templates/base.html
{% extends 'core.html' %}

<!--  -->

{% block content %}

<!--  -->

{% include 'components/header.html' %}

<main id="content">
  <!--  -->

  {% block main %} {% endblock %}

  <!--  -->
</main>

{% include 'components/footer.html' %}

<!--  -->

{% endblock content %}

server/templates/components/footer.html
<footer>
  <small class="copyrights">
    &copy; <span id="currentYear"></span>. All Rights Reserved
  </small>
</footer>

server/templates/components/header.html
<header class="page-header">
  <a class="skip-navigation-link" href="#content">Skip Navigation</a>

  {% include 'components/icon/logo.html' %}
  <!--  -->
  {% include 'components/navigation.html' %}
</header>

server/templates/components/icon/logo.html
{% load static %}

<div class="logo">
  <a href="{% url 'common:index' %}">
    <img src="{% static 'assets/logo.svg' %}" alt="logo" />
  </a>
</div>

server/templates/components/icon/menu.html
{% load static %}

<button
  id="menu-toggle"
  class="menu-toggle"
  aria-expanded="false"
  aria-controls="primary-navigation"
>
  <img src="{% static 'assets/menu.svg' %}" alt="menu-toggle" />
  <span class="visually-hidden">menu-toggle</span>
</button>

server/templates/components/navigation.html
<nav role="navigation" aria-label="Main">
  {% include 'components/icon/menu.html' %}

  <ul id="primary-navigation" class="primary-navigation" data-state="closed">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'common:index' %}"
      
        {% if request.resolver_match.namespace == 'common' %}
        aria-current="page"
        {% endif %}
        > 
        Home 
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'admin:index' %}"

        {% if request.resolver_match.namespace == 'admin' %}
        aria-current="page"
        {% endif %}
        > 
        Admin 
      </a>
    </li>
  </ul>
</nav>

server/templates/core.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />
    <link rel="icon" href="{%  static 'favicon.svg' %}" />
    <script src="{% static 'js/index.js' %}" defer></script>
    <title>Django Web App</title>
  </head>
  <body>
    {% block content %}
    <!--  -->
    {% endblock %}
  </body>
</html>